import os
from dotenv import load_dotenv
load_dotenv()

AZURE_GPT_40_API_KEY = os.getenv('AZURE_GPT_40_API_KEY')
AZURE_GPT_40_API_VERSION = os.getenv('AZURE_GPT_40_API_VERSION')
AZURE_GPT_40_API_END_POINT =  os.getenv('AZURE_GPT_40_API_END_POINT')
AZURE_GPT_40_API_DEVELOPMENT = os.getenv('AZURE_GPT_40_API_DEVELOPMENT')
